version: 1.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu
