version: 1.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root

  ApplicationStop:
    - location: scripts/stop.sh
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu
