version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - cd miniproject4-spring/miniproject04
      - chmod +x gradlew
      - ./gradlew clean build -x test
